import { PersonData } from "../types";

export const isAutogeneratedCardId = (id: string) => {
    return id.split('-').length === 5;
}

export const isHighlighted = (data: PersonData) => {
  const params = new URLSearchParams(window.location.search);
  return (params.get('person_id') === data.id);
}