# Generated by Django 5.2.3 on 2025-06-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personname',
            name='name_type',
            field=models.CharField(blank=True, choices=[('born as', 'Birth'), ('married as', 'Marriage'), ('immigrated as', 'Immigration')], max_length=100),
        ),
    ]
