# Generated by Django 5.2.3 on 2025-06-15 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_personname_name_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenshipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='person.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImmigrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('from_country', models.CharField(max_length=100)),
                ('to_country', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='person.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BirthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='person.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person',), name='unique_birth_per_person')],
            },
        ),
        migrations.CreateModel(
            name='DeathEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('cause', models.CharField(blank=True, max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='person.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person',), name='unique_death_per_person')],
            },
        ),
        migrations.CreateModel(
            name='DivorceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('other_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_as_partner', to='person.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='person.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'other_person', 'date'), name='unique_divorce_per_couple_date')],
            },
        ),
        migrations.CreateModel(
            name='MarriageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('ended', models.BooleanField(default=False)),
                ('other_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_as_partner', to='person.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='person.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'other_person', 'date'), name='unique_marriage_per_couple_date')],
            },
        ),
    ]
