# Generated by Django 5.2.3 on 2025-06-16 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_citizenshipevent_immigrationevent_birthevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('U', 'Unknown'), ('M', 'Male'), ('F', 'Female')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='person',
            name='is_living',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ParentChildRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='person.person')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='person.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='parents',
            field=models.ManyToManyField(related_name='children', through='person.ParentChildRelationship', to='person.person'),
        ),
        migrations.AddConstraint(
            model_name='parentchildrelationship',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='unique_parent_child'),
        ),
    ]
