# Generated by Django 5.2.3 on 2025-06-16 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_person_gender_person_is_living_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthevent',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='person.person'),
        ),
        migrations.AlterField(
            model_name='citizenshipevent',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='person.person'),
        ),
        migrations.AlterField(
            model_name='deathevent',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='person.person'),
        ),
        migrations.AlterField(
            model_name='divorceevent',
            name='other_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_as_partner', to='person.person'),
        ),
        migrations.AlterField(
            model_name='divorceevent',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='person.person'),
        ),
        migrations.AlterField(
            model_name='immigrationevent',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='person.person'),
        ),
        migrations.AlterField(
            model_name='marriageevent',
            name='other_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_as_partner', to='person.person'),
        ),
        migrations.AlterField(
            model_name='marriageevent',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='person.person'),
        ),
    ]
