# Generated by Django 5.2.3 on 2025-06-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_birthevent_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthevent',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='citizenshipevent',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='deathevent',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='divorceevent',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='immigrationevent',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='marriageevent',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='personname',
            name='name_type',
            field=models.CharField(blank=True, choices=[('born as', 'Birth'), ('married as', 'Marriage'), ('immigrated as', 'Immigration')], default='born as', max_length=100),
        ),
    ]
