# Generated by Django 5.2.3 on 2025-06-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_alter_birthevent_date_alter_citizenshipevent_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citizenshipevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deathevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='divorceevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immigrationevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marriageevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
