# Generated by Django 5.2.3 on 2025-06-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_birthevent_date_alter_citizenshipevent_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='parents',
            new_name='children',
        ),
    ]
