# Generated by Django 5.2.3 on 2025-06-21 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_remove_person_parents_person_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='children',
            field=models.ManyToManyField(related_name='parents', through='person.ParentChildRelationship', to='person.person'),
        ),
        migrations.CreateModel(
            name='PersonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='person_attachments/')),
                ('original_filename', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='person.person')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
