# Generated by Django 5.2.3 on 2025-07-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_alter_person_children_personattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personname',
            name='name_type',
            field=models.CharField(blank=True, choices=[('born as', 'Birth'), ('married as', 'Marriage'), ('immigrated as', 'Immigration'), ('other', 'Other')], default='born as', max_length=100),
        ),
    ]
